version: "3"
services:
  nextjs-dev:
    image: ghcr.io/cookify-webapp/cookify-frontend:dev
    restart: unless-stopped
    container_name: "nextjs-dev"
    env_file:
      - ./cookify-frontend/.env.development
    ports:
      - "3001:3001"