name: deploy-fe-prd
on:
  workflow_dispatch:
    inputs:
      deploy-version:
        description: 'Version to deploy'
        required: true
jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: pull images and deploy
        uses: appleboy/ssh-action@master
        env:
          FE_VERSION: ${{ github.event.inputs.deploy-version }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          envs: FE_VERSION
          script: |
            cd cookify-devops/cookify-frontend
            git checkout main
            git pull origin main
            echo "FE_VERSION=${FE_VERSION}" >> .env
            docker rm -f nextjs-prd
            docker-compose up -d
  test:
    needs: deploy
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install modules
        run: npm install
      - name: Run Test
        run: npm run test:prd
  notify:
    name: Discord Notification
    runs-on: ubuntu-20.04
    needs:
      - deploy
      - test
    if: ${{ always() }}
    steps:
      - name: Notify
        uses: nobrayner/discord-webhook@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          discord-webhook: ${{ secrets.DISCORD_WEBHOOK }}
          username: 'Cookify Webapp Bot'
          avatar-url: 'https://i.ibb.co/9nD72C9/Mini-logo-with-bg.png'
          title: '${{ github.workflow }}: {{STATUS}}'
          color-success: '#63AB2A'
          color-failure: '#E00000'
          color-cancelled: '#FFB800'