name: deploy-fe-dev
on:
  push:
    branches:
      - develop
  pull_request:
    branches: 
      - develop
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          tags: ghcr.io/cookify-webapp/cookify-frontend:dev
          context: .
          file: ./Dockerfile-dev
          push: true
  deploy:
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: pull images and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd cookify-devops/cookify-frontend
            git checkout develop
            git pull origin develop
            docker rm -f nextjs-dev
            docker-compose -f docker-compose.dev.yml up -d
  test:
    needs: deploy
    runs-on: ubuntu-20.04
    steps:
      - name: Check Home Page
        run: |
          echo '#!/bin/bash
          retry_times=10
          current_retry=0
          while [ $current_retry -lt $retry_times ]
          do
            curl -s http://cookifywebapp-dev.ddns.net | grep "You need to enable JavaScript to run this app."
            result_status=$?
            let current_retry++
            [ $result_status -eq 0 ] && break
            sleep 10
          done
          exit $result_status' > after_deploy_test.sh
          chmod +x after_deploy_test.sh
          ./after_deploy_test.sh