name: deploy-fe-prd
on:
  workflow_dispatch:
    inputs:
      deploy-version:
        description: 'Version to deploy'
        required: true
jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: refs/tags/${{ github.event.inputs.deploy-version }}
      - name: pull images and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd cookify-devops/cookify-frontend
            git checkout main
            git pull origin main
            docker rm -f nextjs-prd
            docker rmi ghcr.io/cookify-webapp/cookify-frontend:prd
            docker-compose -f docker-compose.prd.yml up -d
  notify:
    name: Discord Notification
    runs-on: ubuntu-20.04
    needs:
      - build
      - deploy
    if: ${{ always() }}
    steps:
      - name: Notify
        uses: nobrayner/discord-webhook@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          discord-webhook: ${{ secrets.DISCORD_WEBHOOK }}
          username: 'Cookify Webapp Bot'
          avatar-url: 'https://i.ibb.co/9nD72C9/Mini-logo-with-bg.png'
          title: '${{ github.workflow }}: {{STATUS}}'
          color-success: '#63AB2A'
          color-failure: '#E00000'
          color-cancelled: '#FFB800'